export const SERVICES = [
  {
    id: "web-platforms",
    title: "Web Platforms & Mobile Apps",
    subtitle: "Product UI + scalable backend",
    theme: "cyan",
    headline: "Launch web & mobile platforms",
    description: "Product-grade UX with scalable services and store-ready builds.",
    proof: ["Production-grade", "Scales cleanly", "Store-ready"],
    timeline: "Prototype 2–4 weeks • Production 6–10 weeks",
    deliverables: "Design tokens + UI kit, API + auth, payments-ready flows, admin & analytics.",
    bestFor: "Founders shipping v1→v2, internal platforms, multi-tenant SaaS.",
    whatYouGet: [
      "Responsive web app (product-grade UI)",
      "Mobile app build (iOS/Android-ready)",
      "Backend services + database schema",
      "Admin panel + role-based access",
      "Analytics + release checklist",
    ],
    process: [
      { title: "Scope & UX map", desc: "Define roles, journeys, and success metrics." },
      { title: "Architecture", desc: "Choose data model, APIs, and scaling path." },
      { title: "Build UI + API", desc: "Iterate in vertical slices with weekly demos." },
      { title: "Hardening", desc: "Perf budgets, security checks, observability." },
      { title: "Launch", desc: "Store submission / rollout plan + post-launch fixes." },
    ],
    tech: ["TypeScript", "Node", "Postgres", "Kubernetes", "React Native"],
    engagement: [
      { type: "Fixed scope", desc: "Well-defined MVP with clear acceptance criteria." },
      { type: "Sprint", desc: "2-week cycles with prioritized backlog." },
      { type: "Retainer", desc: "Ongoing features + reliability improvements." },
    ],
  },
  {
    id: "software-tools",
    title: "Software & Tools (CLI)",
    subtitle: "Install flows + release pipeline",
    theme: "violet",
    headline: "Ship CLI tools teams trust",
    description: "Installation flows, configs, and release pipelines that feel effortless.",
    proof: ["Deterministic installs", "Signed releases", "Docs-first"],
    timeline: "Prototype 1–3 weeks • Production 4–8 weeks",
    deliverables: "CLI commands, installers, config schema, signed builds, versioned docs.",
    bestFor: "Developer tools, internal automation, cross-platform installers.",
    whatYouGet: [
      "CLI command design + help UX",
      "Cross-OS install commands & configs",
      "Release pipeline (test→build→sign→publish)",
      "Telemetry hooks (opt-in)",
      "Versioned docs + examples",
    ],
    process: [
      { title: "Command map", desc: "Define verbs, flags, and expected outputs." },
      { title: "Installer flow", desc: "OS-specific steps + config validation." },
      { title: "Core engine", desc: "Reliable logic with idempotent operations." },
      { title: "Release pipeline", desc: "CI with signing + publish automation." },
      { title: "Supportability", desc: "Logs, error codes, and troubleshooting docs." },
    ],
    tech: ["Rust", "Go", "Node", "GitHub Actions", "Sigstore"],
    engagement: [
      { type: "Fixed scope", desc: "Single tool + v1 install flow." },
      { type: "Sprint", desc: "Extend commands, plugins, and docs." },
      { type: "Retainer", desc: "Long-term maintenance + release cadence." },
    ],
  },
  {
    id: "ai",
    title: "AI (Chat Interfaces)",
    subtitle: "Tools + traces + monitoring",
    theme: "cyan",
    headline: "Deploy AI assistants responsibly",
    description: "Tool-using chat with traceability, guardrails, and monitoring built in.",
    proof: ["Traceable", "Guardrailed", "Evaluated"],
    timeline: "Prototype 2–4 weeks • Production 6–12 weeks",
    deliverables: "Chat UX, tool integrations, source traces, eval suite, monitoring dashboard.",
    bestFor: "Support deflection, sales copilots, ops automation.",
    whatYouGet: [
      "Chat UI + tool panel UX",
      "Knowledge base grounding (docs + CRM/email)",
      "Guardrails (PII, policy, rate limits)",
      "Evaluation & regression harness",
      "Monitoring dashboards + alerting hooks",
    ],
    process: [
      { title: "Use-cases", desc: "Define workflows, tool boundaries, and policies." },
      { title: "Conversation design", desc: "Script happy paths + failure modes." },
      { title: "Tooling", desc: "Connect sources; implement citations and traces." },
      { title: "Eval & hardening", desc: "Offline evals, red-teaming, latency budgets." },
      { title: "Monitoring", desc: "Quality metrics, drift checks, and incident runbooks." },
    ],
    tech: ["RAG", "Vector DB", "Queues", "Observability", "Policy checks"],
    engagement: [
      { type: "Fixed scope", desc: "Single assistant + evaluation framework." },
      { type: "Sprint", desc: "Expand tools, knowledge, and safety." },
      { type: "Retainer", desc: "Ongoing improvements + drift monitoring." },
    ],
  },
  {
    id: "blockchain",
    title: "Blockchain (DeFi & Web3)",
    subtitle: "Smart contracts + dashboards",
    theme: "violet",
    headline: "Build DeFi & Web3 products",
    description: "Smart contracts, wallets, and dashboards for blockchain applications.",
    proof: ["Audited contracts", "Multi-chain", "Production-ready"],
    timeline: "Prototype 3–5 weeks • Production 8–14 weeks",
    deliverables: "Smart contracts, wallet integration, trading dashboards, analytics.",
    bestFor: "DeFi protocols, NFT platforms, Web3 applications.",
    whatYouGet: [
      "Smart contract development & auditing",
      "Wallet integration (MetaMask, WalletConnect)",
      "Trading & analytics dashboards",
      "Multi-chain support (Ethereum, Solana, BSC)",
      "Security audits + deployment pipeline",
    ],
    process: [
      { title: "Protocol design", desc: "Define tokenomics, governance, and mechanics." },
      { title: "Contract development", desc: "Write, test, and optimize smart contracts." },
      { title: "Security audit", desc: "Internal + external security reviews." },
      { title: "Frontend integration", desc: "Connect wallets, transactions, and state." },
      { title: "Launch", desc: "Mainnet deployment + monitoring setup." },
    ],
    tech: ["Solana", "Ethereum", "Rust", "Solidity", "Web3.js"],
    engagement: [
      { type: "Fixed scope", desc: "Single protocol with defined features." },
      { type: "Sprint", desc: "Iterative feature additions." },
      { type: "Retainer", desc: "Ongoing protocol maintenance + upgrades." },
    ],
  },
  {
    id: "security-audit",
    title: "Security & Audit",
    subtitle: "Penetration testing + monitoring",
    theme: "cyan",
    headline: "Secure your infrastructure",
    description: "Comprehensive security audits, penetration testing, and continuous monitoring.",
    proof: ["OWASP compliant", "CVE tracking", "Certified"],
    timeline: "Assessment 1–2 weeks • Remediation 2–6 weeks",
    deliverables: "Audit report, penetration test results, remediation plan, monitoring setup.",
    bestFor: "Pre-launch security review, compliance requirements, ongoing monitoring.",
    whatYouGet: [
      "Code security audit (SAST/DAST)",
      "Penetration testing (infrastructure + application)",
      "Vulnerability assessment & CVE tracking",
      "Security monitoring + incident response",
      "Compliance documentation (SOC2, ISO27001)",
    ],
    process: [
      { title: "Scoping", desc: "Define audit boundaries and threat models." },
      { title: "Assessment", desc: "Automated + manual security testing." },
      { title: "Reporting", desc: "Detailed findings with severity ratings." },
      { title: "Remediation", desc: "Fix critical issues + verify patches." },
      { title: "Monitoring", desc: "Continuous scanning + alerting setup." },
    ],
    tech: ["OWASP ZAP", "Burp Suite", "SonarQube", "Snyk", "Datadog Security"],
    engagement: [
      { type: "Fixed scope", desc: "One-time comprehensive audit." },
      { type: "Sprint", desc: "Quarterly security reviews." },
      { type: "Retainer", desc: "Continuous monitoring + incident response." },
    ],
  },
  {
    id: "hardware",
    title: "Hardware & Devices",
    subtitle: "Product concepts + prototypes",
    theme: "violet",
    headline: "Design hardware products",
    description: "Product concept mockups, industrial design, and prototype development.",
    proof: ["Manufacturable", "User-tested", "Production-ready"],
    timeline: "Concept 2–4 weeks • Prototype 6–12 weeks",
    deliverables: "3D models, technical specs, prototype builds, manufacturing docs.",
    bestFor: "IoT devices, consumer electronics, industrial hardware.",
    whatYouGet: [
      "Product concept + industrial design",
      "3D CAD models + technical drawings",
      "Functional prototype builds",
      "Firmware + embedded software",
      "Manufacturing partner coordination",
    ],
    process: [
      { title: "Concept", desc: "Define use-case, form factor, and constraints." },
      { title: "Industrial design", desc: "CAD modeling + material selection." },
      { title: "Prototyping", desc: "3D printing + PCB assembly." },
      { title: "Testing", desc: "User testing + reliability validation." },
      { title: "Manufacturing", desc: "Production planning + supplier coordination." },
    ],
    tech: ["CAD (Fusion 360)", "PCB Design", "3D Printing", "Embedded C", "MQTT"],
    engagement: [
      { type: "Fixed scope", desc: "Single product concept to prototype." },
      { type: "Sprint", desc: "Iterative design improvements." },
      { type: "Retainer", desc: "Product line development." },
    ],
  },
  {
    id: "cloud-devops",
    title: "Cloud & DevOps",
    subtitle: "Infrastructure + CI/CD",
    theme: "cyan",
    headline: "Scale your infrastructure",
    description: "Cloud architecture, Kubernetes, CI/CD pipelines, and reliability engineering.",
    proof: ["Auto-scaling", "99.9% uptime", "Cost-optimized"],
    timeline: "Setup 2–4 weeks • Migration 4–10 weeks",
    deliverables: "Infrastructure as code, CI/CD pipelines, monitoring, runbooks.",
    bestFor: "Scaling startups, cloud migrations, reliability improvements.",
    whatYouGet: [
      "Cloud architecture (AWS/GCP/Azure)",
      "Kubernetes cluster setup + management",
      "CI/CD pipeline (GitHub Actions, GitLab CI)",
      "Monitoring + observability (Datadog, Grafana)",
      "Cost optimization + auto-scaling",
    ],
    process: [
      { title: "Assessment", desc: "Current state + scaling requirements." },
      { title: "Architecture", desc: "Design cloud infrastructure + data flow." },
      { title: "Implementation", desc: "Deploy IaC + migrate workloads." },
      { title: "Automation", desc: "CI/CD pipelines + deployment automation." },
      { title: "Operations", desc: "Monitoring setup + incident response." },
    ],
    tech: ["Kubernetes", "Terraform", "AWS", "Docker", "Prometheus"],
    engagement: [
      { type: "Fixed scope", desc: "Initial cloud setup + migration." },
      { type: "Sprint", desc: "Infrastructure improvements." },
      { type: "Retainer", desc: "Ongoing DevOps support." },
    ],
  },
  {
    id: "integrations-apis",
    title: "Integrations & APIs",
    subtitle: "Third-party connections",
    theme: "violet",
    headline: "Connect your ecosystem",
    description: "API development, third-party integrations, and data synchronization.",
    proof: ["RESTful", "Rate-limited", "Documented"],
    timeline: "Simple integration 1–2 weeks • Complex 4–8 weeks",
    deliverables: "API endpoints, integration adapters, sync pipelines, documentation.",
    bestFor: "SaaS integrations, payment gateways, CRM/ERP connections.",
    whatYouGet: [
      "RESTful API design + development",
      "Third-party integration adapters",
      "Data sync pipelines + webhooks",
      "API documentation (OpenAPI/Swagger)",
      "Rate limiting + authentication",
    ],
    process: [
      { title: "Integration map", desc: "Define data flow + authentication." },
      { title: "API design", desc: "Endpoint structure + versioning strategy." },
      { title: "Development", desc: "Build adapters + error handling." },
      { title: "Testing", desc: "Integration tests + edge cases." },
      { title: "Documentation", desc: "API docs + integration guides." },
    ],
    tech: ["Node.js", "FastAPI", "GraphQL", "OAuth2", "Webhooks"],
    engagement: [
      { type: "Fixed scope", desc: "Single integration implementation." },
      { type: "Sprint", desc: "Multiple integration rollout." },
      { type: "Retainer", desc: "Integration maintenance + expansion." },
    ],
  },
  {
    id: "data-analytics",
    title: "Data & Analytics",
    subtitle: "Pipelines + dashboards",
    theme: "cyan",
    headline: "Turn data into insights",
    description: "Data pipelines, analytics dashboards, and business intelligence.",
    proof: ["Real-time", "Scalable", "Actionable"],
    timeline: "Pipeline 2–4 weeks • Dashboard 3–6 weeks",
    deliverables: "ETL pipelines, data warehouse, BI dashboards, reporting.",
    bestFor: "Business intelligence, product analytics, operational reporting.",
    whatYouGet: [
      "Data pipeline design + ETL jobs",
      "Data warehouse setup (Snowflake, BigQuery)",
      "Analytics dashboards (Tableau, Looker, Metabase)",
      "Real-time streaming pipelines",
      "Custom reporting + alerting",
    ],
    process: [
      { title: "Data audit", desc: "Identify sources + quality issues." },
      { title: "Pipeline design", desc: "ETL architecture + transformations." },
      { title: "Implementation", desc: "Build pipelines + data models." },
      { title: "Dashboards", desc: "Design visualizations + reports." },
      { title: "Optimization", desc: "Performance tuning + cost reduction." },
    ],
    tech: ["dbt", "Airflow", "Snowflake", "Kafka", "Tableau"],
    engagement: [
      { type: "Fixed scope", desc: "Single data pipeline + dashboard." },
      { type: "Sprint", desc: "Expand analytics coverage." },
      { type: "Retainer", desc: "Ongoing pipeline maintenance." },
    ],
  },
  {
    id: "qa-reliability",
    title: "QA & Reliability",
    subtitle: "Testing + monitoring",
    theme: "violet",
    headline: "Ship with confidence",
    description: "Comprehensive testing, reliability engineering, and quality assurance.",
    proof: ["Automated", "Coverage >80%", "SLA-backed"],
    timeline: "Test setup 2–4 weeks • Ongoing monitoring",
    deliverables: "Test suites, load testing, monitoring, incident runbooks.",
    bestFor: "Pre-launch QA, reliability improvements, SLA guarantees.",
    whatYouGet: [
      "Automated test suites (unit, integration, e2e)",
      "Load & performance testing",
      "Chaos engineering + failure scenarios",
      "Monitoring + alerting setup",
      "Incident response runbooks",
    ],
    process: [
      { title: "Test strategy", desc: "Define coverage goals + test pyramid." },
      { title: "Automation", desc: "Build test suites + CI integration." },
      { title: "Performance", desc: "Load testing + bottleneck identification." },
      { title: "Monitoring", desc: "Observability + SLO/SLA setup." },
      { title: "Hardening", desc: "Chaos tests + disaster recovery." },
    ],
    tech: ["Playwright", "k6", "Chaos Mesh", "Datadog", "PagerDuty"],
    engagement: [
      { type: "Fixed scope", desc: "Initial test suite + monitoring." },
      { type: "Sprint", desc: "Expand test coverage." },
      { type: "Retainer", desc: "Ongoing QA + reliability engineering." },
    ],
  },
  {
    id: "ui-ux",
    title: "UI/UX Design",
    subtitle: "Design systems + prototypes",
    theme: "cyan",
    headline: "Design products users love",
    description: "User research, design systems, prototyping, and visual design.",
    proof: ["User-tested", "Accessible", "Scalable"],
    timeline: "Research 1–2 weeks • Design 3–6 weeks",
    deliverables: "Design system, prototypes, component library, design tokens.",
    bestFor: "Product redesigns, design systems, user research.",
    whatYouGet: [
      "User research + persona development",
      "Information architecture + user flows",
      "High-fidelity prototypes (Figma)",
      "Design system + component library",
      "Accessibility compliance (WCAG 2.1)",
    ],
    process: [
      { title: "Research", desc: "User interviews + competitive analysis." },
      { title: "Information architecture", desc: "Sitemaps + user flows." },
      { title: "Wireframes", desc: "Low-fi sketches + user testing." },
      { title: "Visual design", desc: "High-fi mockups + design system." },
      { title: "Handoff", desc: "Developer-ready specs + component library." },
    ],
    tech: ["Figma", "Design Tokens", "Storybook", "Accessibility Tools"],
    engagement: [
      { type: "Fixed scope", desc: "Single product design." },
      { type: "Sprint", desc: "Iterative design improvements." },
      { type: "Retainer", desc: "Design system maintenance + evolution." },
    ],
  },
  {
    id: "retainers",
    title: "Ongoing Support & Retainers",
    subtitle: "Long-term partnership",
    theme: "violet",
    headline: "Partner for the long term",
    description: "Dedicated engineering capacity for ongoing development and support.",
    proof: ["Dedicated team", "SLA-backed", "Flexible"],
    timeline: "3/6/12 month engagements",
    deliverables: "Weekly sprints, monthly reviews, priority support.",
    bestFor: "Growing companies, product evolution, continuous improvement.",
    whatYouGet: [
      "Dedicated engineering capacity",
      "Weekly sprint cycles + demos",
      "Priority support + bug fixes",
      "Architecture evolution + tech debt",
      "Monthly performance reviews",
    ],
    process: [
      { title: "Onboarding", desc: "Team integration + codebase audit." },
      { title: "Sprint planning", desc: "Prioritize backlog with stakeholders." },
      { title: "Execution", desc: "Weekly sprints with demos." },
      { title: "Review", desc: "Monthly retrospectives + planning." },
      { title: "Evolution", desc: "Continuous improvement + scaling." },
    ],
    tech: ["Your stack", "Best practices", "Modern tooling"],
    engagement: [
      { type: "Part-time (20h/week)", desc: "Maintenance + small features." },
      { type: "Full-time (40h/week)", desc: "Active development + support." },
      { type: "Team (80h+/week)", desc: "Dedicated engineering team." },
    ],
  },
];
